<a href="https://colab.research.google.com/github/MrAbbas07/edureka/blob/main/AI%26ML_lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import keyword
print(keyword.kwlist)
a=len(keyword.kwlist)
print(a)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']
35


In [ ]:
print("Hello Abbas <3")
"""
multi
line
comment
"""
print("Hello CSG Peaople")

Hello Abbas <3
Hello CSG Peaople


In [ ]:
a=50
b=50
c=a+b
print(c)
c
x="Hello peeps"
x

100


'Hello peeps'

In [ ]:
#creating a list with constructor()

In [ ]:
a=([1,2,3,4,5])
b=([2,4,7.0,6,8])
c=(["Hello","Student"])
print(a)
print(b)
print(c)
type(a)

[1, 2, 3, 4, 5]
[2, 4, 7.0, 6, 8]
['Hello', 'Student']


list

In [ ]:
#Creating list with heterogenous data

In [ ]:
a=(["Hello",8,9,20.77])
a

['Hello', 8, 9, 20.77]

In [ ]:
#Creating list using range functions:

In [ ]:
L=list(range(0,6))
print(L)

[0, 1, 2, 3, 4, 5]


In [ ]:
#Creating a list without constructor():

In [ ]:
days=["monday","tuesday","wednesday","thursday","friday","saturday","sunday"]
days

['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']

In [ ]:
#Lab2

In [ ]:
#negative indexing
days[-1]

'sunday'

In [ ]:
#list slicing
days[1:4]

['tuesday', 'wednesday', 'thursday']

In [ ]:
#list slicing with step size
days[1:4:2]

['tuesday', 'thursday']

In [ ]:
days=["monday","tuesday","wednesday","thursday","friday","saturday","sunday"]
len(days)

7

In [ ]:
numbers=(1,2,3,4,5,6,7,8)
max(numbers)

8

In [ ]:
min(numbers)

1

In [ ]:
sum(numbers)

36

In [ ]:
import random
numbers=[11,22,33,44,55,66,77,88,99,00]
random.shuffle(numbers)
print(numbers)

[33, 55, 66, 77, 0, 44, 99, 11, 88, 22]


In [ ]:
#examples on operastors

a=[1,2,3]
b=[4,5,6]
c=a+b
print(c)

[1, 2, 3, 4, 5, 6]


In [ ]:
a=[10,20]
b=3*a
print(b)

[10, 20, 10, 20, 10, 20]


In [ ]:
days=["monday","tuesday","wednesday","thursday","friday","saturday","sunday"]
"wednesday" in days

True

In [ ]:
days=["monday","tuesday","wednesday","thursday","friday","saturday","sunday"]
"wednesday" not in days

False

In [ ]:
days=["monday","tuesday","wednesday","thursday","friday","saturday","sunday"]
"abbas" in days

False

In [ ]:
days=["monday","tuesday","wednesday","thursday","friday","saturday","sunday"]
"abbas" not in days

True

In [ ]:
a="Arshiya"
b="Arshiya"
a is b

True

In [ ]:
a="Arshiya"
b="Lubna"
a is b

False

In [ ]:
days=["monday","tuesday","wednesday","thursday","friday","saturday","sunday"]
del[days[1]]
days

['monday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']

In [ ]:
#Methods

In [ ]:
a=["a","b","c","d","e"]
print(a)
a.append("e")
print(a)

['a', 'b', 'c', 'd', 'e']
['a', 'b', 'c', 'd', 'e', 'e']


In [ ]:
list=["red","white","pink","black"]
print(list)
list.clear()
print(list)

['red', 'white', 'pink', 'black']
[]


In [ ]:
z=[1,3,4,5,1,3,6,1,4,7,1,4,8]
print(z)
z.count(1)

[1, 3, 4, 5, 1, 3, 6, 1, 4, 7, 1, 4, 8]


4

In [ ]:
A=[1,2,3,4,5]
B=[6,7,8,9,10]
print(A)
print(B)
A.extend(B)
print(A)

[1, 2, 3, 4, 5]
[6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
#Tuples

In [ ]:
#creating a tuple
a=(5,)
print(type(a))

<class 'tuple'>


In [ ]:
b=[1,2,3,4,5,]
print(b)
print(type(b))

[1, 2, 3, 4, 5]
<class 'list'>


In [ ]:
mix=["Hello",786,23.323]
print(mix)
print(type(mix))

['Hello', 786, 23.323]
<class 'list'>


In [ ]:
#Creating items of tuple
z=(1,2,3,4,"Hello")
print(z[4])

Hello


In [ ]:
#Dictionary

In [ ]:
a={
    "name":"SAM",
    "age":20,
    "Education":"BTech"
}
print(a)

{'name': 'SAM', 'age': 20, 'Education': 'BTech'}


In [ ]:
len(a)

3

In [ ]:
type(a)

dict

In [ ]:
x=a.keys()
y=a.values()
z=a.items()
print(x)
print(y)
print(z)

dict_keys(['name', 'age', 'Education'])
dict_values(['SAM', 20, 'BTech'])
dict_items([('name', 'SAM'), ('age', 20), ('Education', 'BTech')])


In [ ]:
#Python sets

In [ ]:
#example
set1={1,2,3,4}
print(set1)

{1, 2, 3, 4}


In [ ]:
#duplicates not allowed
set={1,2,3,4,1,2,34,4,1,3,3,4,5,7}
print(set)

{1, 2, 3, 4, 34, 5, 7}


In [ ]:
len(set)

7

In [ ]:
type(set)

set

In [ ]:
import numpy as np
print(np.__version__)

1.23.5


In [ ]:
#1D array
import numpy as np

In [ ]:
A1=np.array([1,2,3,4])
print(A1)

[1 2 3 4]


In [ ]:
type(A1)

numpy.ndarray

In [ ]:
A1.shape

(4,)

In [ ]:
A1.size

4

In [ ]:
#2D array
A2=np.array([[1,2,3,4],[5,6,7,8,]])
print(A2)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(type(A2))
print(A2.size)
print(A2.shape)
print(A2.ndim)

<class 'numpy.ndarray'>
8
(2, 4)
2


In [ ]:
#3D array

A3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(A3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
print(type(A3))
print(A3.size)
print(A3.shape)


<class 'numpy.ndarray'>
9
(1, 3, 3)



In [2]:
import numpy as np
z1=np.zeros(3)
z1

array([0., 0., 0.])

In [3]:
#changing data type

z1=np.zeros(3,dtype=int)
z1

array([0, 0, 0])

In [6]:
print(z1.shape)
print(z1.size)
print(z1.ndim)
print(type(z1))

(3,)
3
1
<class 'numpy.ndarray'>


In [7]:
z2=np.zeros((3,4))
z2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
z2=np.zeros((3,4),dtype=int)
z2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [10]:
print(z2.shape)
print(z2.size)
print(z2.ndim)
print(type(z2))

(3, 4)
12
2
<class 'numpy.ndarray'>


In [11]:
z3=np.zeros((2,3,4),dtype=int)
z3

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [12]:
print(z3.shape)
print(z3.size)
print(z3.ndim)
print(type(z3))

(2, 3, 4)
24
3
<class 'numpy.ndarray'>


In [14]:
 #1D ones array
 import numpy as np
 a1=np.ones(3,dtype=int)
 a1

array([1, 1, 1])

In [17]:
print(a1.shape)
print(a1.size)
print(a1.ndim)

(3,)
3
1


In [16]:
a2=np.ones([3,4],dtype=int)
a2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [18]:
print(a2.shape)
print(a2.size)
print(a2.ndim)

(3, 4)
12
2


In [23]:
a3=np.ones([4,2,3],dtype=int)
a3

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [24]:
print(a3.shape)
print(a3.size)
print(a3.ndim)

(4, 2, 3)
24
3


In [25]:
#1D full array
f1=np.full(3,9)
f1

array([9, 9, 9])

In [27]:
f1=np.full(3,9,dtype=float)
f1


array([9., 9., 9.])

In [28]:
print(f1.shape)
print(f1.size)
print(f1.ndim)

(3,)
3
1


In [30]:
#2D full array
f2=np.full([2,3],9)
f2

array([[9, 9, 9],
       [9, 9, 9]])

In [32]:
#3D full array
f3=np.full([4,2,3],10)
f3


array([[[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]]])

In [34]:
f3=np.full([4,2,3],10,dtype=int)
f3

array([[[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]]])

In [36]:
f3=np.full([4,2,3],10,dtype='str')

f3

array([[['1', '1', '1'],
        ['1', '1', '1']],

       [['1', '1', '1'],
        ['1', '1', '1']],

       [['1', '1', '1'],
        ['1', '1', '1']],

       [['1', '1', '1'],
        ['1', '1', '1']]], dtype='<U1')

In [37]:
a=np.array([1,2,3])
b=np.array([1,2,3])

add=np.add(a,b)
add

array([2, 4, 6])

In [39]:
a=np.array([5,10,20])
b=np.array([4,8,10])

sub=np.subtract(a,b)
sub

array([ 1,  2, 10])

In [41]:
a=np.array([5,10,20])
b=np.array([4,8,10])

mul=np.multiply(a,b)
mul

array([ 20,  80, 200])

In [42]:
a=np.array([5,10,20])
b=np.array([4,8,10])

div=np.divide(a,b)
div

array([1.25, 1.25, 2.  ])

In [44]:
a=np.array([5,10,20])
b=np.array([4,8,10])

mod=np.mod(a,b)
mod

array([1, 2, 0])

In [45]:
a=np.array([5,10,20])
b=np.array([4,8,10])

power=np.power(a,b)
power

array([           625,      100000000, 10240000000000])