<a href="https://colab.research.google.com/github/MrAbbas07/edureka/blob/main/AI%26ML_lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import keyword
print(keyword.kwlist)
a=len(keyword.kwlist)
print(a)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']
35


In [ ]:
print("Hello Abbas <3")
"""
multi
line
comment
"""
print("Hello CSG Peaople")

Hello Abbas <3
Hello CSG Peaople


In [ ]:
a=50
b=50
c=a+b
print(c)
c
x="Hello peeps"
x

100


'Hello peeps'

In [ ]:
#creating a list with constructor()

In [ ]:
a=([1,2,3,4,5])
b=([2,4,7.0,6,8])
c=(["Hello","Student"])
print(a)
print(b)
print(c)
type(a)

[1, 2, 3, 4, 5]
[2, 4, 7.0, 6, 8]
['Hello', 'Student']


list

In [ ]:
#Creating list with heterogenous data

In [ ]:
a=(["Hello",8,9,20.77])
a

['Hello', 8, 9, 20.77]

In [ ]:
#Creating list using range functions:

In [ ]:
L=list(range(0,6))
print(L)

[0, 1, 2, 3, 4, 5]


In [ ]:
#Creating a list without constructor():

In [ ]:
days=["monday","tuesday","wednesday","thursday","friday","saturday","sunday"]
days

['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']

In [ ]:
#Lab2

In [ ]:
#negative indexing
days[-1]

'sunday'

In [ ]:
#list slicing
days[1:4]

['tuesday', 'wednesday', 'thursday']

In [ ]:
#list slicing with step size
days[1:4:2]

['tuesday', 'thursday']

In [ ]:
days=["monday","tuesday","wednesday","thursday","friday","saturday","sunday"]
len(days)

7

In [ ]:
numbers=(1,2,3,4,5,6,7,8)
max(numbers)

8

In [ ]:
min(numbers)

1

In [ ]:
sum(numbers)

36

In [ ]:
import random
numbers=[11,22,33,44,55,66,77,88,99,00]
random.shuffle(numbers)
print(numbers)

[33, 55, 66, 77, 0, 44, 99, 11, 88, 22]


In [ ]:
#examples on operastors

a=[1,2,3]
b=[4,5,6]
c=a+b
print(c)

[1, 2, 3, 4, 5, 6]


In [ ]:
a=[10,20]
b=3*a
print(b)

[10, 20, 10, 20, 10, 20]


In [ ]:
days=["monday","tuesday","wednesday","thursday","friday","saturday","sunday"]
"wednesday" in days

True

In [ ]:
days=["monday","tuesday","wednesday","thursday","friday","saturday","sunday"]
"wednesday" not in days

False

In [ ]:
days=["monday","tuesday","wednesday","thursday","friday","saturday","sunday"]
"abbas" in days

False

In [ ]:
days=["monday","tuesday","wednesday","thursday","friday","saturday","sunday"]
"abbas" not in days

True

In [ ]:
a="Arshiya"
b="Arshiya"
a is b

True

In [ ]:
a="Arshiya"
b="Lubna"
a is b

False

In [ ]:
days=["monday","tuesday","wednesday","thursday","friday","saturday","sunday"]
del[days[1]]
days

['monday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']

In [ ]:
#Methods

In [1]:
a=["a","b","c","d","e"]
print(a)
a.append("e")
print(a)

['a', 'b', 'c', 'd', 'e']
['a', 'b', 'c', 'd', 'e', 'e']


In [9]:
list=["red","white","pink","black"]
print(list)
list.clear()
print(list)

['red', 'white', 'pink', 'black']
[]


In [8]:
z=[1,3,4,5,1,3,6,1,4,7,1,4,8]
print(z)
z.count(1)

[1, 3, 4, 5, 1, 3, 6, 1, 4, 7, 1, 4, 8]


4

In [11]:
A=[1,2,3,4,5]
B=[6,7,8,9,10]
print(A)
print(B)
A.extend(B)
print(A)

[1, 2, 3, 4, 5]
[6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [12]:
#Tuples

In [13]:
#creating a tuple
a=(5,)
print(type(a))

<class 'tuple'>


In [15]:
b=[1,2,3,4,5,]
print(b)
print(type(b))

[1, 2, 3, 4, 5]
<class 'list'>


In [16]:
mix=["Hello",786,23.323]
print(mix)
print(type(mix))

['Hello', 786, 23.323]
<class 'list'>


In [17]:
#Creating items of tuple
z=(1,2,3,4,"Hello")
print(z[4])

Hello


In [18]:
#Dictionary

In [19]:
a={
    "name":"SAM",
    "age":20,
    "Education":"BTech"
}
print(a)

{'name': 'SAM', 'age': 20, 'Education': 'BTech'}


In [21]:
len(a)

3

In [22]:
type(a)

dict

In [23]:
x=a.keys()
y=a.values()
z=a.items()
print(x)
print(y)
print(z)

dict_keys(['name', 'age', 'Education'])
dict_values(['SAM', 20, 'BTech'])
dict_items([('name', 'SAM'), ('age', 20), ('Education', 'BTech')])


In [24]:
#Python sets

In [25]:
#example
set1={1,2,3,4}
print(set1)

{1, 2, 3, 4}


In [30]:
#duplicates not allowed
set={1,2,3,4,1,2,34,4,1,3,3,4,5,7}
print(set)

{1, 2, 3, 4, 34, 5, 7}


In [31]:
len(set)

7

In [32]:
type(set)

set

In [34]:
import numpy as np
print(np.__version__)

1.23.5


In [35]:
#1D array
import numpy as np

In [36]:
A1=np.array([1,2,3,4])
print(A1)

[1 2 3 4]


In [38]:
type(A1)

numpy.ndarray

In [39]:
A1.shape

(4,)

In [40]:
A1.size

4

In [42]:
#2D array
A2=np.array([[1,2,3,4],[5,6,7,8,]])
print(A2)

[[1 2 3 4]
 [5 6 7 8]]


In [45]:
print(type(A2))
print(A2.size)
print(A2.shape)
print(A2.ndim)

<class 'numpy.ndarray'>
8
(2, 4)
2


In [46]:
#3D array

A3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(A3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [47]:
print(type(A3))
print(A3.size)
print(A3.shape)


<class 'numpy.ndarray'>
9
(1, 3, 3)

